add_rules("mode.debug", "mode.release")
set_languages("c++20")
set_warnings("all", "error")

add_requires("spdlog")
add_includedirs("src", "libs")

target("gameak")
set_kind("static")
add_files("src/gameak/**.cpp")
add_headerfiles("src/(gameak/**.h)")
add_packages("spdlog")

target("gameak_test")
set_kind("binary")
set_default(false)
add_deps("gameak")
add_includedirs("src", "libs")
add_files("tests/**.cpp")
add_packages("spdlog")
add_tests("default")
